name: tbib_flutter_simple_ui
description: Custom simple ui login - register - forget password - file uploader
  - file downloader - etc
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.0.0
  tbib_file_uploader: ^1.0.2

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/svg/
# fonts:
#   - family: Roboto
#     fonts:
#     # - asset: assets/fonts/Roboto/Roboto-Black.ttf
#       #   weight: 900
#       # - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
#       #   weight: 800
#       - asset: assets/fonts/Roboto/Roboto-Bold.ttf
#         weight: 700
#       - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
#         weight: 600
#       - asset: assets/fonts/Roboto/Roboto-Medium.ttf
#         weight: 500
#       - asset: assets/fonts/Roboto/Roboto-Regular.ttf
#         weight: 400
#       - asset: assets/fonts/Roboto/Roboto-Light.ttf
#         weight: 300
#   - family: SF Pro Display
#     fonts:
#     # - asset: assets/fonts/Roboto/Roboto-Black.ttf
#       #   weight: 900
#       # - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
#       #   weight: 800
#       - asset: assets/fonts/sf-pro/SFPRODISPLAY-Bold.otf
#         weight: 700
#       - asset: assets/fonts/sf-pro/SFPRODISPLAY-SemiBoldItalic.otf
#         weight: 600
#       - asset: assets/fonts/sf-pro/SFPRODISPLAY-Medium.otf
#         weight: 500
#       - asset: assets/fonts/sf-pro/SFPRODISPLAY-Regular.otf
#         weight: 400
#       - asset: assets/fonts/sf-pro/SFPRODISPLAY-LightItalic.otf
#         weight: 300
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
